ingredients_db = [
    {"name": "Salicylic Acid", "concerns": [{"name": "Acne", "severity": ["moderate", "severe"]}], "avoid_with": ["Retinol", "Vitamin C"], "routine_stage": ["PM"], "product_type": "Cleanser", "max_use": "3-4 times weekly", "description": "Exfoliates within pores, reduces sebum."},
    {"name": "Benzoyl Peroxide", "concerns": [{"name": "Acne", "severity": ["moderate", "severe"]}], "avoid_with": ["Retinol"], "routine_stage": ["PM"], "product_type": "Treatment", "max_use": "Daily", "description": "Kills acne-causing bacteria."},
    {"name": "Niacinamide", "concerns": [{"name": "Acne", "severity": ["mild"]}, {"name": "Oiliness", "severity": ["mild", "moderate"]}, {"name": "Hyperpigmentation", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Regulates sebum and reduces inflammation."},
    {"name": "Azelaic Acid", "concerns": [{"name": "Acne", "severity": ["mild", "moderate"]}, {"name": "Hyperpigmentation", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Anti-inflammatory and reduces redness."},
    {"name": "Vitamin C", "concerns": [{"name": "Aging", "severity": ["mild"]}, {"name": "Hyperpigmentation", "severity": ["mild", "moderate"]}], "avoid_with": ["Retinol", "Salicylic Acid"], "routine_stage": ["AM"], "product_type": "Serum", "max_use": "Daily", "description": "Brightens skin and inhibits melanin production."},
    {"name": "Kojic Acid", "concerns": [{"name": "Hyperpigmentation", "severity": ["mild", "moderate"]}], "avoid_with": ["Vitamin C"], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Inhibits tyrosinase to lighten dark spots."},
    {"name": "Alpha Arbutin", "concerns": [{"name": "Hyperpigmentation", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Inhibits tyrosinase to lighten dark spots."},
    {"name": "Retinol", "concerns": [{"name": "Aging", "severity": ["mild", "moderate", "severe"]}], "avoid_with": ["Salicylic Acid", "Vitamin C", "Benzoyl Peroxide"], "routine_stage": ["PM"], "product_type": "Serum", "max_use": {"mild": "1-2 times weekly", "moderate": "2-3 times weekly", "severe": "3-4 times weekly"}, "description": "Stimulates collagen production and reduces wrinkles."},
    {"name": "Peptides", "concerns": [{"name": "Aging", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Boosts collagen and elastin production."},
    {"name": "Hyaluronic Acid", "concerns": [{"name": "Dryness", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Attracts and retains moisture."},
    {"name": "Ceramides", "concerns": [{"name": "Dryness", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Moisturizer", "max_use": "Daily", "description": "Restores skin barrier and prevents moisture loss."},
    {"name": "Centella Asiatica", "concerns": [{"name": "Sensitive Skin", "severity": ["mild", "moderate"]}], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Serum", "max_use": "Daily", "description": "Calms inflammation and soothes irritation."},
    {"name": "Generic Cleanser", "concerns": [], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Cleanser", "description": "Gently cleanses the skin."},
    {"name": "Generic Moisturizer", "concerns": [], "avoid_with": [], "routine_stage": ["AM", "PM"], "product_type": "Moisturizer", "description": "Hydrates and protects the skin."},
    {"name": "Generic Sunscreen", "concerns": [], "avoid_with": [], "routine_stage": ["AM"], "product_type": "Sunscreen", "description": "Provides protection against UV damage."}
]